### ISSUE TITLE
Makefile 新增 OpenJDK 環境建置

### ISSUE THREAD

**Issue by ntut-xuan** [ntut-xuan/NuOJ#15]
### 期望

由於 Sandbox 支持 Java 語言，故我們需要 Java 相關的環境，需要在 Makefile 上新增 OpenJDK 18 環境建置的步驟。

### 實作

 - [ ] 其他
     - [ ] 在 Makefile 上新增 OpenJDK 18 環境建置

**Comment by c1ydehhx** [comment]
Close issue since we use dockerfile instead of makefile.
